font:
  maruMonica: /font/MaruMonica.ttf
  purisaBold: /font/PurisaBold.ttf

player:
  images:
    boyUp1: /player/boy_up_1.png
    boyUp2: /player/boy_up_2.png
    boyDown1: /player/boy_down_1.png
    boyDown2: /player/boy_down_2.png
    boyLeft1: /player/boy_left_1.png
    boyLeft2: /player/boy_left_2.png
    boyRight1: /player/boy_right_1.png
    boyRight2: /player/boy_right_2.png

npc:
  images:
    merchantDown1: /npc/merchant_down_1.png
    merchantDown2: /npc/merchant_down_2.png
    bigrock: /npc/bigrock.png
    oldMan:
      down1: /npc/oldman_down_1.png
      down2: /npc/oldman_down_2.png
      up1: /npc/oldman_up_1.png
      up2: /npc/oldman_up_2.png
      left1: /npc/oldman_left_1.png
      left2: /npc/oldman_left_2.png
      right1: /npc/oldman_right_1.png
      right2: /npc/oldman_right_2.png

monster:
  images:
    greenSlime:
      down1: /monster/greenslime_down_1.png
      down2: /monster/greenslime_down_2.png

items:
  images:
    boots: /objects/boots.png
    chest: /objects/chest.png
    door: /objects/door.png
    key: /objects/key.png
    heartFull: /objects/heart_full.png
    heartHalf: /objects/heart_half.png
    heartBlank: /objects/heart_blank.png

world:
  mapPath: /maps/worldV2.txt
  tile:
    images:
      water:
        "0": /tiles/water00.png
        "1": /tiles/water01.png
        "2": /tiles/water02.png
        "3": /tiles/water03.png
        "4": /tiles/water04.png
        "5": /tiles/water05.png
        "6": /tiles/water06.png
        "7": /tiles/water07.png
        "8": /tiles/water08.png
        "9": /tiles/water09.png
        "10": /tiles/water10.png
        "11": /tiles/water11.png
        "12": /tiles/water12.png
        "13": /tiles/water13.png
      grass:
        "0": /tiles/grass00.png
        "1": /tiles/grass01.png
      road:
        "0": /tiles/road00.png
        "1": /tiles/road01.png
        "2": /tiles/road02.png
        "3": /tiles/road03.png
        "4": /tiles/road04.png
        "5": /tiles/road05.png
        "6": /tiles/road06.png
        "7": /tiles/road07.png
        "8": /tiles/road08.png
        "9": /tiles/road09.png
        "10": /tiles/road10.png
        "11": /tiles/road11.png
        "12": /tiles/road12.png
      wall: /tiles/wall.png
      earth: /tiles/earth.png
      tree: /tiles/tree.png
      sand: /tiles/sand.png
      table: /tiles/table01.png
      floor: /tiles/floor01.png
      hut: /tiles/hut.png

sound:
  path:
    backgroundSong: /sound/BlueBoyAdventure.wav
    coin: /sound/coin.wav
    powerUp: /sound/powerup.wav
    unlock: /sound/unlock.wav
    fanfare: /sound/fanfare.wav
